# Site settings
title: Bartek Wilczyński
email: contact@xperienced.com.pl
url: https://xperienced.com.pl
description: "IT consultant and entrepreneur with over 10 years of experience in a variety of medium-size line of business applications, mostly in .NET technology."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2980b9 #18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: XPERIENCED Bartłomiej Wilczyński
  location: Location
  social: Get in Touch
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/bwilczyn
  - title: linkedin
    url: http://linkedin.com/in/bwilczyn
  - title: youtube
    url: https://youtube.com/user/bwilczyn
  - title: github
    url: http://github.com/xperienced

# Postal address (add as many lines as necessary)
address:
  - line: Warsaw, Poland

# Credits content
credits: 'Created using Freelancer template - a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
